apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: app1
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
  - targetPort: 80
    port: 80
